### PR TITLE
update influxdata GPG key after rotation

### LINKED ISSUE #164: Influxdata key rotation causing failure
**Describe the bug**
Influxdata has rotated their public key causing this role and currently installs to no longer work

**Installation method/version**
Galaxy

**Ansible Version**

```
ansible [core 2.13.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/xxxxxxxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

**Targetted hosts**
Concerns the following OS(es):
* Debian

**Expected behavior**
A graceful way to handle the key rotation

**Additional context**
https://www.influxdata.com/blog/linux-package-signing-key-rotation/

### PR DESCRIPTION
**Pull request by Tetha**
**Description of PR**

This PR updates the apt_key to the newly rotated influxdata key. I've tested the change by locally modifying your galaxy role to the new key and then my molecule checks run again.

**Type of change**

Bugfix Pull Request

**Fixes an issue**

This fixes #164

### CODE REVIEW

**Comment by fastman** [comment]
@Tetha  Why not `influxdata-archive_compat.key` as per https://www.influxdata.com/blog/linux-package-signing-key-rotation/?

**Comment by Tetha** [comment]
@fastman well, the page says:

> What is the difference between influxdata-archive.key and influxdata-archive_compat.key?
>
> The influxdata-archive.key signing key utilizes a modern primary/subkey approach that     will be incorporated into future Linux packaging updates. The influxdata-archive_compat.key can verify packages signed with the influxdata-archive.key and has the widest APT and RPM compatibility. Please use the influxdata-archive_compat.key at this time.

So I've been looking around a bit, and this has been supported by apt and gpg for a long time, hence I figured to use the thing that's the desired, future looking solution instead of a compat workaround. 

If the tests fail or more concerns appear, I can change it, but that'll incur another change down the road once the compat layer gets removed or changed.

**Comment by dj-wasabi** [comment]
I updated the master branch, can you rebase from master and retry?

**Comment by dj-wasabi** [comment]
Thanks! (I'll remove Debian 8 as it seems eol).

**Comment by dj-wasabi** [comment]
Hey @fastman I created tag `0.14.0`

**Pull request merged**
