### PR TITLE
MacOS support

### PR DESCRIPTION
**Pull request by carlba**
**Description of PR**
Provides MacOS support for the role. The brew service system works a bit different than most other linux/bsd service system in that it is only meant to be run as your local user account. I looked into creating a telegraf user and running the service as that but that doesn't seem inline with brew service best practices. On MacOs it is therefore required to specify a `telegraf_mac_user` which should be your main user account.

I also added role_name to the role meta since this is nowadays required to get the role to present correctly on Ansible Galaxy.

**Type of change**
Feature Pull Request

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @carlba 

Can you update the documentation about the user part so other people can benefit from it as well?

Thanks!
Werner

**Comment by carlba** [comment]
Sorry for the delay where do you suggest that I add the information?

**Comment by carlba** [comment]
Is this text sufficient?

**Comment by dj-wasabi** [comment]
@carlba Fine by me! Thanks! 👍

**Pull request merged**
