### PR TITLE
use version_compare filter …

### PR DESCRIPTION
**Pull request by lhoss**
…(more readable, stable and no extra set_fact required)

ps: more 'useful' PR coming (adding new agent settings 👍 )

### CODE REVIEW

**Comment by lhoss** [comment]
ps: Changes were already tested (of course I'm using ansible >v2 )

and the travis build did not fail due to my change:
```
0.25s$ molecule test
ERROR: Driver missing, install docker-py.
```

**Comment by dj-wasabi** [comment]
About Travis, I know. I'm fixing it now.

**Comment by dj-wasabi** [comment]
And thanks!

**Comment by lhoss** [comment]
wow thx for fast merging ... I was about to write the 'requirements.yml' now I can switch back to the original role 👍

**Pull request merged**
