### PR TITLE
Added property telegraf_agent_docker_image_version for using a specific version of the Docker image

### PR DESCRIPTION
**Pull request by dj-wasabi**
Added property telegraf_agent_docker_image_version for using a specific version of the Docker image

**Description of PR**

**Type of change**

Bugfix Pull Request

**Fixes an issue**

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @jgeusebroek 

I added a property named `telegraf_agent_docker_image_version` which defaults uses the value from `telegraf_agent_version` but can be set to an other tag like `latest`.

Can you check if this works for you?

Kind regards,
Werner

**Comment by jgeusebroek** [comment]
Awesome Werner, I will test it tonight!

**Comment by jgeusebroek** [comment]
Seems to be working fine! I made something that fetched the current version from the docker image.
https://github.com/jgeusebroek/ansible-telegraf/tree/docker_version

But in the end it doesn't matter because there is no docker telegraf image < 0.10 :joy:.

**Comment by dj-wasabi** [comment]
@jgeusebroek haha! LOL

Thanks for testing, I'll merge this PR. 👍

**Pull request merged**
